INT-1287 and INT-1337
polarityio/threatconnect-ioc-submission pull request #20
Opened 2024-11-20 13:18 UTC by ahaias-tc

I have combined INT-1287 and INT-1337 in a single PR.

2024-11-21 13:34 UTC, sarus requested changes
@ahaias-tc Functionality works great.  Left some comments in various places.  Please let me know if you have any questions!

2024-11-21 14:25 UTC, ahaias-tc commented on templates/block.hbs
> +      <span class="p-key">WhoIs</span>
Might be some differences between Mac and Windows? It looks aligned on my side, but I will definitely try the change you suggested. The reason I am asking this is that I specifically added some styling to make it aligned.

2024-11-22 07:19 UTC, sarus commented on templates/block.hbs
> +      <span class="p-key">WhoIs</span>
@ahaias-tc Could definitely be a OS difference.  We've even seen differences in Chrome across OSes when it comes to CSS styling.  Are you using Safari to test?  At least on Windows, it seems like the label block element also needs to have the flex box styling to center align the text and checkbox (not just the parent container).

2024-11-22 11:17 UTC, ahaias-tc commented on templates/block.hbs
> +      <span class="p-key">WhoIs</span>
No, I am testing on Chrome. I hate Safari

2024-11-26 07:23 UTC, sarus requested changes
@ahaias-tc The package-lock has conflicts and is preventing merging.  Since no changes were made to the package.json I would revert the package-lock the version in the `develop` branch to resolve the conflict.

Otherwise changes look good!

2024-11-27 15:45 UTC, sarus requested changes
@ahaias-tc Sorry for all the back and forth but the integration development checklist isn't passing.  To merge into develop you'll need to bump the version in the `package.json` file (and possible modify the version in the package-lock as well).

Since you added a new feature I would suggest bumping the version to `3.1.0`

![Uploading image.png…]()

2024-12-03 13:15 UTC, sarus approved these changes
@ahaias-tc Looks great!

2024-12-03 16:36 UTC, merged